---
title: "Introducción reporte"
format: html
---

Existe una constante duda en el mercado financiero, sobre los enfoques del análisis técnico y el fundamental (trading vs value investing), métodos que son clave a la hora de invertir dinero, al punto en que tanto académicos como profesionales no han podido encontrar una respuesta clara. Un ejemplo de esto es Benjamin Graham (Inversor, autor, y profesor), conocido como el padre del "value investing", quien afirma que el trading es meramente especulativo, mientras que el value investing es una inversión, por otro lado, los méritos del trading son reconocidos por quienes lo practican llegando a ganar abismales sumas de dinero.

Tanto Benjamin Graham como los traders (quienes practican el trading) tienen argumentos para creer que su punto de visto es el correcto, pero cual es la pregunta que ambos quieren responder, ¿Es el trading mejor que el value investing o viceversa?, ¿Cuál es más rentable?, ¿Existe la certeza de que, si funciono ayer, también funcionara mañana?, ¿Como podemos maximizar las ganancias en ambos casos?, ¿Cuál es la clave de cada método?, ¿Son compatibles?. Responder estas preguntas nos entrega un punto de vista interesante, ya que se puede trazar una ruta inicial objetiva a través de la estadística, logrando un método base para lo que se conoce hoy en día como análisis bursátil.

Con el objetivo de encontrar el mejor método para maximizar ganancias de manera eficiente. Analizaremos los 2 métodos, trading y value investing, con los factores que podrían ser clave para resolver las preguntas antes planteadas, con el fin de entender si algún método es mejor que otro, o compatibles. Este trabajo estará divido en distintas secciones, primero se hará un análisis particular con los datos de distintos mercados financiero, tanto para el trading como para el value investing, sentando las bases y estructuras de cada método. Luego construiremos las estrategias que mejor se adapten para maximizar ganancias y eficiencia. Avanzaremos con puntos máximos y mínimos de entrada, así ahondando en el tema de que si conocemos los resultados el éxito está garantizado. Y antes de concluir haremos 3 experimentos para cada mercado financiero, que se desarrollaran durante el transcurso del proyecto. Y para terminar se concluirán los resultados obtenidos, junto con opiniones al respecto. El trabajo incluye conocimientos específicos de economía, estadística, y análisis bursátil.
